### ISSUE TITLE
Error while building docker image useing dockerfile

### ISSUE THREAD

**Issue by Manash-UAS** [Gradiant/openverso-images#16]
Hello,

I tried building the docker image using the docker file, but getting error on step 16. 
Attached is the screenshot. Can you please tell where I am getting it wrong.

![Error_dockerfile](https://user-images.githubusercontent.com/56870468/151550737-b00b7228-91f4-4a8c-9b78-adfa2f99ca9a.png)

**Comment by cgiraldo** [comment]
Hello,
How did you run your docker build?
If you enter open5gs folder an run docker build from there, It should work.

Example for building the open5gs 2.4.0 version:openverso:

```
cd open5gs
docker build --build-arg version=2.4.0 -t open5gs:2.4.0 .
```

**Comment by avrodriguezgrad** [comment]
Hi @Manash-UAS,

Can you test the deployment with the docker-compose given in the open5gs folder? Would you tell us if you have the same errors with that?

**Comment by avrodriguezgrad** [comment]
We are going to close the issue, if you want to open it again because you still have the problem, do it!
Regards
