### ISSUE TITLE
openverso/open5gs:2.6.1 images restarting

### ISSUE THREAD

**Issue by databatt** [Gradiant/openverso-images#207]
Hi,

After upgrading openverso/open5gs:2.6.1. most of containers keeps restarting all the time.

I suppose after upgrading to 2.6.1 (Release 17 open5gs) something changed and there is a problem in the images

As I suppose, the docker images versions of dockerhub are aligned to open5gs upgrades. After 2.6.1, Open5gs is in Rel-17, and as I see, the corresponding images with version >2.6.1 show problem.

Could you confirm if you have notice or something I could do?

Tested in ubuntu 22 with docker compose as provided in open5gs-and-ueransim folder, upgrading from 2.3.2 to 2.6.1.

Thanks !

**Comment by cgiraldo** [comment]
open5gs > 2.6.0 sets tls enabled by default. We don't include tls certificates in our image, so if you don't disable tls in open5gs configuration files, the services don't start.

I updated the openverso/open5gs:2.6.3 dockerhub image to disable tls in its configuration files.

Try with this image version, It should fix the problem.

**Comment by databatt** [comment]
Hello Carlos,

I have test 2.6.3 and 2.6.4 and the restarting problem is solved. Thanks! Although keeps in a loop with some issue as you can see in the image, the containers keep active . Is it something important the messeges in the picture? They are warnings but just to know.

![image](https://github.com/Gradiant/openverso-images/assets/33227735/cc09480d-e385-416b-bbfc-797fb6af6f96)

Thaks for the support!

**Comment by cgiraldo** [comment]
Yes, they are important. 
There are some configuration changes also in version 2.6.4, so please, use 2.6.3.

**Comment by databatt** [comment]
hello,

Unfortunatelly this problem appear in 2.6.3 too, so with this version the problem appear too.

:(

**Comment by cgiraldo** [comment]
The problem was with the base image. 
We have updated from debian bullseye to debian bookworm, but it seems to be a problem with libcurl or libidn.

We have reverted the 2.6.4 image to debian bullseye in the meanwhile. 
Just try with version 2.6.4.

We have also updated the docs/open5gs-and-ueransim files to make it work.

Hope that helps.
