### ISSUE TITLE
Credentials dockerhub UERANSIM image

### ISSUE THREAD

**Issue by databatt** [Gradiant/openverso-images#209]
I have been testing the images for Webui UERANSIM WebUI with normal credentials. admin/1432 but it is not working. Could you provide or inform what are the correct credentials for the ueransim image please?

Example: https://hub.docker.com/r/openverso/open5gs-webui/tags

Thanks in advance

**Comment by cgiraldo** [comment]
open5gs-webui image is ready for production (not example users included).

Configure  the container with an environment variable  `NODE_ENV=development` to start it in development mode which includes an admin user with 1432 password.
