### ISSUE TITLE
Ping Test in open5Gs and Ueransim docker compose

### ISSUE THREAD

**Issue by rodrigosanzsanz** [Gradiant/openverso-images#216]
Hello,

Thanks for the support. Following the steps in this documentation: https://github.com/Gradiant/openverso-images/tree/main/docs/open5gs-and-ueransim

Under the Test step. It seems the gnb and ue part is ok and new UE can be registered but, i don´t see the 'uesimtun0' interface created. How can I make a test to check if a ping is trought the UE-gNB interface? Is everything ok with the docker compose and interface is correctly created?

image: openverso/ueransim:3.2.6
 command: ['ue','-n','3']

I hope you can check the issue , or tell me if any step is issing.

Thanks in advance

**Comment by rodrigosanzsanz** [comment]
All images are up in the same Linux Ubuntu machines, maybe  it is a problem to be in the same machine to create the TUN interface ¿?

**Comment by cgiraldo** [comment]
Hi Rodrigo,

There were several changes in the images and the tutorial was not updated accordingly.

We have to update the MCC provided in ueransim to be the same as the default used in the core (999).

There were also problems in how we register the users in the core. A new script is included.

Please, follow the new README.md of the tutorial. It should now works.

**Comment by rodrigosanzsanz** [comment]
These are great news Carlos! Let me check with the new changes, and thanks for your great support.

**Comment by rodrigosanzsanz** [comment]
Hello Carlos,

After some tests, I see several issues solved. User registration script seems works properly and the MCC issue and documentation is fixed.

Unfortunatelly, I see uesimtun0 interface is not created after ues1/ues2 'exec' part is executed (docker compose -f gnb1.yaml exec ues1 /bin/bash) . Now I don´t see errors in this part but because the 'uesimtun0' is not created, when I try tracerout or ping to reach internet, the result is as in the image. (ping: SO_BINDTODEVICE: No such device)

Is it possible any issue in TUN configuration, or DN config data , than makes uesimun interface not up?

Thanks in advance.

![Captura de pantalla 2023-10-25 a las 14 19 57](https://github.com/Gradiant/openverso-images/assets/133344742/0da62411-0e27-4b7c-833c-a4a322cc9571)

**Comment by cgiraldo** [comment]
I uploaded this morning a new image trying to fix a random error that happens with scp / nrf services:

[https://github.com/open5gs/open5gs/issues/2028](https://github.com/open5gs/open5gs/issues/2028
)

You can inspect the logs to see if you are hitting the previous error `Invalid API name [nnrf-disc]`:

```
docker compose -f ngc.yaml logs | grep ERROR
```

To solve it, please, try updating your local copy of the docker image prior to doing the `compose up`

```
docker pull openverso/open5gs:2.6.4
```

**Comment by rodrigosanzsanz** [comment]
Hi,

I have tried with the new open5gs:2.6.4 image making the pull and following the steps. With same result.
There is no "Invalid API name... " error in my case, just the following:
![Captura de pantalla 2023-10-25 a las 16 15 26](https://github.com/Gradiant/openverso-images/assets/133344742/b87e070f-5b81-4e0c-866d-265a61b8d067)

On the other hand, after launching the gNB1 and ue1 script, the UE seems not possible to register, indicating PLMN_NOT_ALLOWED

![Captura de pantalla 2023-10-25 a las 16 27 26](https://github.com/Gradiant/openverso-images/assets/133344742/8ad3ef32-058f-4b23-b636-364ba1867241)

I will try to check MCC,NCC info config files to look for any issue... any other idea? :)

Meanwhile a UE can not make a correct registration I suppose next TUN interface step is secondary...

Thanks Carlos

**Comment by rodrigosanzsanz** [comment]
Sorry Carlos, There was an error by my side, now it is working...
![image](https://github.com/Gradiant/openverso-images/assets/133344742/7690b0b0-e257-4824-ad39-eac5a70e07a7)

I will try to go deeply in UPF selection scenarios :)

And later we plan to follow the helm openverso version if you recommend it for research.

Thanks for support!

**Comment by cgiraldo** [comment]
Glad to hear that!

Of course I recommend you to try our kubernetes helm charts. We use them internally in our 5G research projects and find them useful enough to share them with the open source community. 
Also the openverso-charts tutorials are more updated that the ones in this repo 😅.

Good luck!
