### ISSUE TITLE
Upgrade to Open5Gs v2.7.0

### ISSUE THREAD

**Issue by rodrigosanzsanz** [Gradiant/openverso-images#223]
Hello!

Is there any plan to update images in dockerhub for Open5gs version 2.7.0 ? 
I need some of upgrades of this version about UPF selection.

If there´s no plan can I handle with the Dockerfile included in this path?
https://github.com/Gradiant/openverso-images/blob/main/images/open5gs/image_info.sh

Thanks.

**Comment by rodrigosanzsanz** [comment]
Genial Alvaro! Wow!

Thats sounds great! I will be expecting the new images, because I think there are some changes in the UPF definition for SMF (the server and client definitions...). And it is key for us to test UPF selection with v2.7.0 and samf subnet in upf configs.

Thanks!Great!

**Comment by avrodriguezgrad** [comment]
Hi Rodrigo,

The new images are released! Get in touch with me if you have any issues.

Thanks!
